FROM rust:1.86 AS builder
COPY ./radardevice /app/
WORKDIR /app
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && apt-get install -y openssl ca-certificates && rm -rf /var/lib/apt/lists/*
RUN openssl version
WORKDIR /app
COPY --from=builder /app/target/release/radardevice .
COPY ./radardevice/dev2_signals.csv .
ENTRYPOINT ["./radardevice", "--id", "87900a57-c21e-4746-8105-68f2c673ceed", "--latitude", "240.12", "--longitude", "108.78", "--file-name", "/app/dev2_signals.csv"]